name: Norminette

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hanshazairi/42-norminette-action@v1.1.0
